<!-- 
    - show KPIs
    - show period filters
    - show clients
    - actions
        - add lead
        - add opportunity
        - add quote
        - add job
        - convert lead
        - convert opportunity
        - convert quote
    - get sales figures
-->